### ISSUE TITLE
Only for samsung

### ISSUE THREAD

**Issue by yjojovasuka** [mazen-salah/Smart-TV-Remote-Control#2]
Is this exclusive to Samsung devices? What about other TVs? 
The universal TV remote that you described in description

**Comment by mazen-salah** [comment]
Thanks for your interest in the project! Please note that this project has been discontinued by me. However, you're more than welcome to contribute and add support for other device models. Keep in mind that each TV OS has its own APIs, so some customization may be needed depending on the device. Feel free to fork the repo and make any enhancements you see fit.
